# Habilita la Nueva Arquitectura de React Native (obligatorio para Reanimated 4.x)
newArchEnabled=true

# Optimizaciones de memoria para el build
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# Hermes (motor JS optimizado para React Native)
hermesEnabled=true